# Generated by Django 5.0.2 on 2024-02-22 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplikacjablog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(max_length=250, unique_for_date='publish'),
        ),
    ]
